name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.2
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.0
      - name: Install dependencies
        run: poetry install
      - name: Test
        run: make test
